import pygame

def init():
    global img
    global dt
    global keys
    global tickFunction
    global fontBase
    global fontSmall
    global volMusic
    global volSound
    global invulnerability
    global scrollX
    global scrollY
    global stageObjects
    global stageCosmetic
    global sortedSprites
    global shadowSprites
    global stageClear
    global player
    global debugString
    global musicTitle
    global musicGame
    global musicGame2
    global startStageClear
    global stageClearTimer
    global bossScrollX
    global playerHealthMax